config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#top"

  resources :users
  resources :shops do
    resources :posts
    get :search, on: :collection
  end
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :users
  has_many :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :shops
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,length:{maximum:15}
  validates :taste, presence: true,length:{maximum:100}
  validates :atmosphere, presence: true,length:{maximum:100}
  validates :service, presence: true,length:{maximum:100}
  belongs_to :shop
  belongs_to :user
end

app/models/pricerange.rb
class Pricerange < ApplicationRecord
  has_many :shops
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  validates :title, presence: true,length:{maximum:15}
  validates :description, presence: true
  validates :name, presence: true

  belongs_to :user
  belongs_to :genre
  belongs_to :pricerange
  has_many :posts, dependent: :destroy
  belongs_to :address
  mount_uploader :image, ImageUploader

  def self.search(shop_params)
    shops = Shop.all
    shops = shops.where("name LIKE ?", "%#{shop_params[0]}%") if shop_params[0].present?
    shops = shops.where(genre_id: shop_params[1]) if shop_params[1].present?
    shops = shops.where(pricerange_id: shop_params[2]) if shop_params[2].present?
    shops = shops.where(address_id: shop_params[3]) if shop_params[3].present?
    shops.order(id: "asc")
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :store_name, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence:true,
                   length:{maximum:15}
  
  VALID_EMAIL_REGEX = /[a-zA-Z0-9._+]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*/
  validates :email, presence:true,
                    uniqueness: true,
             format:{with:VALID_EMAIL_REGEX}

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  validates :password, presence:true, 
                       length: {minimum: 8, maximum: 32,},
                       format:{with:VALID_PASSWORD_REGEX}
  validates :sex, presence:true
  validates :age, presence:true 
  validates :address_id, presence:true
  has_secure_password 

  has_many :shops
  has_many :posts
  belongs_to :address
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @shop = Shop.find(params[:shop_id])
    @post = @shop.posts.new
    @user = current_user
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @post = @shop.posts.new(post_params)
    if @post.save
      redirect_to shop_path(@shop), notice:"投稿ありがとうございます！"
    else
      flash[alert] = "投稿失敗・・・"
      redirect_to new_shop_post_path(@shop)
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    @post = @shop.posts.find(params[:shop_id])
    @user = current_user
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @post = @shop.posts.find(params[:id])
    if @post.user_id == current_user.id
      @post.update(post_params)
      redirect_to shop_path(@shop), notice:"クチコミを編集しました!"
    else
      flash[:alert] = "権限がありません！"
      render :show
    end  
  end

  def destroy
    shop = Shop.find(params[:id])
    post = shop.posts.find(params[:shop_id])
    if post.user_id == current_user.id
      post.destroy
      redirect_to shop_path(shop), notice:"クチコミを削除しました!"
    else  
      flash[:alert] = "権限がありません！"
      render :show
    end   
  end
  

  private
  def post_params
    params.require(:post).permit(:title, :taste, :atmosphere, :service, :shop_id, :user_id, :rate)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, notice:"ログインしました"
    else
      flash.now[:alert] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path, alert:"ログアウトしました"
  end
 
  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    if @shop.save
      redirect_to shops_path, notice: "投稿ありがとうございます！"
    else
      flash.now[:alert] = "投稿失敗・・・"
      render :new
    end
  end

  def index
    @shops = Shop.find(Post.group(:shop_id).order("avg(rate) desc").limit(5).pluck(:shop_id))
    @rate = Post.group(:shop_id).average(:rate)
  end

  def show
    @shop = Shop.find(params[:id])
    @posts = @shop.posts.page(params[:page]).per(3)
    @rate = Post.group(:shop_id).average(:rate)
    @count = Post.group(:shop_id).count(:rate)
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.user_id == current_user.id
      @shop.update(shop_params)
      redirect_to shop_path(@shop), notice: "編集が完了しました！"
    else
      flash[:alert] = "権限がありません！"
      render :show
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    if shop.user_id == current_user.id
      shop.destroy
      redirect_to shops_path, notice: "削除されました！"
    else
      flash[:alert] = "権限がありません！"
      render :show
    end
  end

  def search
    shop_params = [params[:name], params[:genre_id], params[:pricerange_id], params[:address_id]]
    @shops = Shop.search(shop_params).page(params[:page]).per(3)
    @rate = Post.group(:shop_id).average(:rate)
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :image, :title, :description, :genre_id, :pricerange_id, :address_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice:"登録が完了しました"
    else
      flash.now[:alert] = "登録に失敗しました。"
      render new_user_path
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :sex, :address_id, :image )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %> 
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>飲食店最強クチコミキュレーションサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'jquery_raty', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Bon appetit!!", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="nav_target">
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <h4 class="user-name"><%= current_user.name %> 様ようこそ！</h4>
        <li><%= link_to "クチコミランキング", shops_path, class:"btn btn-default" %></li>
        <li><%= link_to "店舗一覧＆検索", search_shops_path, class:"btn btn-default" %></li>
        <li><%= link_to "店舗投稿", new_shop_path, class:"btn btn-default" %></li>
        <li><%= link_to "プロフィール", user_path(current_user), class:"btn btn-default" %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete, class:"btn btn-danger" %></li>
      <% else %> 
        <h4 class="user-name">ゲスト 様ようこそ！</h4>
        <li><%= link_to "クチコミランキング", shops_path, class:"btn btn-default" %></li>
        <li><%= link_to "店舗一覧＆検索", search_shops_path, class:"btn btn-default" %></li>
        <li><%= link_to "新規登録", new_user_path, class:"btn btn-success" %></li>
        <li><%= link_to "ログイン", login_path, class:"btn btn-warning" %></li>
      <% end %>  
      </ul>
    </div>
  </div>
</nav>
      <body>
      <div class= "notifications">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
      </div>  
      <script>
        $(function(){
          $(".alert").fadeOut(7000);
        })
      </script> 

        <%= yield %>
        
      </body>
      <div class="footer">
        <h2>©️ Food Mania</h2>
      </div> 
    </div>
  </div> 
</html>

app/views/pages/top.html.erb
<div class="background-image-container">
  <div class="row">
    <div class="col-lg-12 title text-center">
      Bon appetit!!
    </div> 
  </div>   
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center text-white"> Bon appetit!!(召し上がれ!!)は飲食店の口コミ共有型検索サービスです。</h1>
    </div>
  </div>  
  <div class="row">
    <div class="col-lg-4 text-center text-white">
      <h2 class="bg-success text-black">リアルなクチコミ</h2>
      <p>多くのクチコミを来店前にチェック！<br>もう行ってから後悔する事がなくなります!</p>
    </div>
    <div class="col-lg-4 text-center text-white">
      <h2 class="bg-info text-black">絞り込み検索可能</h2>
      <p>店舗名はもとより「価格」「ジャンル」<br>「クチコミ」等々、様々なフィルターで検索が可能！</p>
    </div>
    <div class="col-lg-4 text-center text-white">
      <h2 class="bg-danger text-black">優良店舗のみ</h2>
      <p>当サイトは登録ユーザーの方の投稿のみ掲載！<br>投稿店舗は一定の基準をクリアしております！</p>
    </div>
  </div>
</div>  

app/views/posts/_form.html.erb
<%= form_with(model: [@shop, @post]) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :"タイトル", class:"text-white" %>
    <%= f.text_field :title, class:"form-control", placeholder:"クチコミのタイトルを入力(15文字以内で入力)" %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :"評価", class:"text-white" %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'post[rate]',
    half: true,
  });
  </script> 
  <div class="form-group">
    <%= f.label :"料理やメニューに関するクチコミ", class:"text-white" %>
    <%= f.text_area :taste, class:"form-control", :size=>"50x5", placeholder:"料理に関するクチコミ内容を入力(100文字まで)" %>
  </div>
  <div class="form-group">
    <%= f.label :"店内に雰囲気や装飾に関するクチコミ", class:"text-white" %>
    <%= f.text_area :atmosphere, class:"form-control", :size=>"50x5", placeholder:"店内に関するクチコミ内容を入力(100文字まで)" %>
  </div>
  <div class="form-group">
    <%= f.label :"接客やサービスに関するクチコミ", class:"text-white" %>
    <%= f.text_area :service, class:"form-control", :size=>"50x5", placeholder:"接客やサービスに関するクチコミ内容を入力(100文字まで)" %>
  </div>
    <%= f.hidden_field :shop_id, value: @shop.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit "登録する！", class:"btn btn-success form-control"  %>
<% end %>

app/views/posts/edit.html.erb
<div class="background-image-container">
  <div class="row"> 
    <div class="col-md-offset-4 col-md-4">
      <h3 class="text-center text-white">口コミ編集</h3>
        <%= render "form" %>
    </div>  
  </div>
</div>

app/views/shops/_form2.html.erb
  <div class="col-md-3">
    <%= image_tag @shop.image.url, class:"img-responsive center-block"%>
  </div>  
  <div class="col-md-9 post-text">
    <div class="col-md-4 text-center post-parts">
      <店舗名>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <料理ジャンル>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.genre.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <キャッチコピー>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.title%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <地域>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.address.prefectures%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <平均単価>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.pricerange.price%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ件数>
    </div>  
    <div class="col-md-8 text-center post-parts">
      <%= @count[@shop.id] %>件
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ平均点>
    </div>
    <div class="col-md-8 text-center post-parts">  
      <%= @rate[@shop.id] %>点
    </div>
  </div>  
  <div class="col-md-12 description-text border">
    <%= @shop.description %>
  </div>  
</div>  
<div class="col-md-12 text-center h1 bg-info">
  みんなのクチコミ
</div> 
<% @shop.posts.each do |p|%>
  <div class="row row-eq-height posts-show balloon4">
    <div class="col-md-4">
      <%= image_tag p.user.image.url, class:"img center-block"%>
    </div>
    <div class="col-md-8  ">  
      <h4 class="md-4">評価：<%= p.rate %>点 | <%= p.title %></h4>
        <!--星評価-->
      <div id="star-rate-<%= p.id %>"></div>
        <script>
        $('#star-rate-<%= p.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= p.rate %>,
        });
        </script>
      <div class="col-md-12">
        <p class="font-weight-bold">料理やメニューに関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.taste%>  
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">店内の雰囲気や装飾に関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.atmosphere%>
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">接客やその他サービスに関して</p>
      </div> 
      <div class="col-md-12">   
        <%= p.service%>
      </div>  
      <% if current_user && current_user.id == p.user.id%>
        <div class="col-md-3">   
          <%= link_to "クチコミ編集", edit_shop_post_path(p), class:"btn btn-success"%>
        </div> 
        <div class="col-md-3 col-md-offset-2">   
          <%= link_to "クチコミ削除", shop_post_path(p), method: :delete, data: {confirm: "本当に削除しますか？"},  class:"btn btn-warning"%>
        </div> 
      <% else %>
      <% end %>
    </div> 
  </div>   
<% end %> 

app/views/shops/_show_form.html.erb
  <div class="col-md-3">
    <%= image_tag @shop.image.url, class:"img-responsive center-block"%>
  </div>  
  <div class="col-md-9 post-text">
    <div class="col-md-4 text-center post-parts">
      <店舗名>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <料理ジャンル>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.genre.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <キャッチコピー>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.title%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <地域>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.address.prefectures%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <平均単価>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.pricerange.price%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ件数>
    </div>  
    <div class="col-md-8 text-center post-parts">
      <% if @count[@shop.id] == nil %>
        0件
      <% else %>  
        <%= @count[@shop.id] %>件
      <% end %>  
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ平均点>
    </div>
    <div class="col-md-8 text-center post-parts">  
      <% if @rate[@shop.id] == nil %>
        ---点
      <% else %>  
        <%= @rate[@shop.id].round(2) %>点
      <% end %>  
    </div>
  </div>  
  <div class="col-md-12 description-text border">
    <%= @shop.description %>
  </div>  
</div>  
<div class="col-md-12 text-center h1 bg-info">
  みんなのクチコミ
</div> 
<% @shop.posts.each do |p|%>
  <div class="row row-eq-height posts-show balloon4">
    <div class="col-md-4">
      <%= image_tag p.user.image.url, class:"img center-block"%>
    </div>
    <div class="col-md-8  ">  
      <h4 class="md-4">評価：<%= p.rate %>点 | <%= p.title %></h4>
        <!--星評価-->
      <div id="star-rate-<%= p.id %>"></div>
        <script>
        $('#star-rate-<%= p.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= p.rate %>,
        });
        </script>
      <div class="col-md-12">
        <p class="font-weight-bold">料理やメニューに関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.taste%>  
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">店内の雰囲気や装飾に関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.atmosphere%>
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">接客やその他サービスに関して</p>
      </div> 
      <div class="col-md-12">   
        <%= p.service%>
      </div>  
      <% if current_user && current_user.id == p.user.id%>
        <div class="col-md-3">   
          <%= link_to "クチコミ編集", edit_shop_post_path(p), class:"btn btn-success"%>
        </div> 
        <div class="col-md-3 col-md-offset-2">   
          <%= link_to "クチコミ削除", shop_post_path(p), method: :delete, data: {confirm: "本当に削除しますか？"},  class:"btn btn-warning"%>
        </div> 
      <% else %>
      <% end %>
    </div> 
  </div>   
<% end %> 
<%= paginate @posts %>

app/views/shops/edit.html.erb
<div class="background-image-container">
  <div class="row"> 
    <div class="col-md-offset-4 col-md-4">
      <h3 class="text-center text-white">店舗編集</h3>
      <%= render "new_edit_form"%>
      <p><%= link_to "店舗クチコミ画面に戻る", shop_path(@shop) %></p>
    </div>  
  </div>
</div>

app/views/shops/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center bg-danger">
       店舗クチコミ
      </h1>
    </div>
  </div>
  <div class="row post-row row-eq-height ">  
  <% if current_user && current_user.id == @shop.user_id%>
    <div class="col-md-6  text-center  ">
      <%= link_to "店舗を編集する", edit_shop_path(@shop), class:"btn btn-success" %>
    </div>
    <div class="col-md-6  text-center ">
      <%= link_to "店舗を削除する", shop_path(@shop), method: :delete, data: {confirm: "本当に削除しますか？"} , class:"btn btn-warning" %>
    </div>
    <%= render "show_form" %>
    <div class="col-md-12 text-center">
      <%= link_to "口コミを投稿する", new_shop_post_path(@shop), class:"btn btn-default" %>
    </div>
  <% elsif current_user %>
    <%= render "show_form" %>
    <div class="col-md-12 text-center">
      <%= link_to "口コミを投稿する", new_shop_post_path(@shop), class:"btn btn-default d-block" %>
    </div>
  <% else %>
    <%= render "show_form" %>
  <% end %>  
</div>  

app/views/shops/show_form.html.erb
  <div class="col-md-3">
    <%= image_tag @shop.image.url, class:"img-responsive center-block"%>
  </div>  
  <div class="col-md-9 post-text">
    <div class="col-md-4 text-center post-parts">
      <店舗名>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <料理ジャンル>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.genre.name%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <キャッチコピー>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.title%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <地域>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.address.prefectures%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <平均単価>
    </div>
    <div class="col-md-8 text-center post-parts">
      <%= @shop.pricerange.price%>
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ件数>
    </div>  
    <div class="col-md-8 text-center post-parts">
      <%= @count[@shop.id] %>件
    </div>
    <div class="col-md-4 text-center post-parts">
      <クチコミ平均点>
    </div>
    <div class="col-md-8 text-center post-parts">  
      <%= @rate[@shop.id] %>点
    </div>
  </div>  
  <div class="col-md-12 description-text border">
    <%= @shop.description %>
  </div>  
</div>  
<div class="col-md-12 text-center h1 bg-info">
  みんなのクチコミ
</div> 
<% @shop.posts.each do |p|%>
  <div class="row row-eq-height posts-show balloon4">
    <div class="col-md-4">
      <%= image_tag p.user.image.url, class:"img center-block"%>
    </div>
    <div class="col-md-8  ">  
      <h4 class="md-4">評価：<%= p.rate %>点 | <%= p.title %></h4>
        <!--星評価-->
      <div id="star-rate-<%= p.id %>"></div>
        <script>
        $('#star-rate-<%= p.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= p.rate %>,
        });
        </script>
      <div class="col-md-12">
        <p class="font-weight-bold">料理やメニューに関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.taste%>  
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">店内の雰囲気や装飾に関して</p>
      </div> 
      <div class="col-md-12"> 
        <%= p.atmosphere%>
      </div>
      <div class="col-md-12">
        <p class="font-weight-bold">接客やその他サービスに関して</p>
      </div> 
      <div class="col-md-12">   
        <%= p.service%>
      </div>  
      <% if current_user && current_user.id == p.user.id%>
        <div class="col-md-3">   
          <%= link_to "クチコミ編集", edit_shop_post_path(p), class:"btn btn-success"%>
        </div> 
        <div class="col-md-3 col-md-offset-2">   
          <%= link_to "クチコミ削除", shop_post_path(p), method: :delete, data: {confirm: "本当に削除しますか？"},  class:"btn btn-warning"%>
        </div> 
      <% else %>
      <% end %>
    </div> 
  </div>   
<% end %> 

app/views/users/show.html.erb
<div class="container">
  <div class="row row-eq-height bg-info"> 
    <div class="col-md-12">
      <h1 class="text-center">プロフィール</h1>
    </div>  
    <div class="col-md-offset-1 col-md-4">
      <% if @user.image %>
        <%= image_tag @user.image.url, class:"img-responsive center-block" %>
      <% else %>
        <%= image_tag "noimage.png", class:"img-responsive center-block" %> 
      <% end %>
    </div>
    <div class="col-md-offset-1 col-md-6">
      <div class="form-group profile-text">
        名前：
        <%= @user.name%>
      </div>
      <div class="form-group profile-text">
        メールアドレス：
        <%= @user.email%>
      </div>
      <div class="form-group profile-text">
        年齢：
        <%= @user.age%>代
      </div>
      <div class="form-group profile-text">
        性別：
        <%= @user.sex%>
      </div>
      <div class="form-group profile-text">
        地域：
        <%= @user.address.prefectures%>
      </div>
      <div class="form-group profile-text">
        <%= link_to "プロフィール編集", edit_user_path(current_user)%>
      </div> 
    </div>  
  </div>
</div>